package org.namofo.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table article_category.
 */
public class ArticleCategory implements Serializable{

    private Long id;
    private String name;

    public ArticleCategory() {
    }

    public ArticleCategory(Long id) {
        this.id = id;
    }

    public ArticleCategory(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
